---
Name: mysite
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SilverStripe\View\SSViewer:
  themes:
    - '/app-theme/dist'
    - '$default'
SilverStripe\i18n\i18n:
  default_locale: 'en_US'

BenManu\StyleGuide\StyleGuideController:
  paths: 'app-theme/src/sass/'
  css_files:
    - 'app-theme/dist/css/style.css'
  js_files:
    - 'app-theme/dist/js/script.min.js'

StevieMayhew\SilverStripeSVG\SVGTemplate:
  base_path: 'app-theme/dist/svg/'
  default_extra_classes:
    - 'svg'

DNA\DNARaygun\RaygunHandler:
  app_name: 'DEFAULT_RECIPE'
